[WIP] Evaluate nested expressions
powdr-labs/powdr pull request #1346
Opened 2024-05-03 15:52 UTC by georgwiese

2024-05-06 10:57 UTC, lvella requested changes
Maybe add a test?

2024-05-06 12:05 UTC, chriseth approved these changes
But as Lucas said, maybe add a test

2024-05-07 10:08 UTC, chriseth approved these changes

2024-05-07 10:12 UTC, lvella approved these changes

2024-05-07 10:35 UTC, merged