Remove query functions
powdr-labs/powdr pull request #1746
Opened 2024-09-02 17:50 UTC by chriseth

2024-09-11 13:38 UTC, chriseth commented on executor/src/witgen/mod.rs
> +// TODO change this so that it has functions
Created issue here: https://github.com/powdr-labs/powdr/issues/1789

2024-09-12 10:00 UTC, lvella requested changes
It seems the `Option` is not necessary and using the `&mut` field "just works" (apparently rebind is automatic).

2024-09-12 12:53 UTC, lvella approved these changes

2024-09-13 13:14 UTC, chriseth commented on std/prover.asm
> +    Query::Output(fd, b) => provide_if_unknown(column, row, || { output_byte(fd, b); 0 }),
The bug was that the system actually expects that we set the value to zero, and that was also the former behaviour.

2024-09-13 13:55 UTC, lvella approved these changes

2024-09-13 14:15 UTC, merged