Git ignore `.cargo`
powdr-labs/powdr pull request #1767
Opened 2024-09-06 15:02 UTC by georgwiese

This way, one can add a `.cargo/config.toml` with the content:

```toml
[build]
rustflags = ["-C", "target-cpu=native"]
```

and doesn't have to think of setting it manually.

2024-09-06 15:51 UTC, Schaeff requested changes
How about using a `config.toml` in your `$HOME/.cargo`? This way we can still have a project level config, and it gets merged with your local one.

2024-09-06 15:52 UTC, Schaeff commented
[Reference](https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure)

2024-09-12 16:21 UTC, lvella commented
But we currently don't have a project level config shared by everyone, and I think that is a good thing that `.cargo` is local, because not everybody uses the same architecture for development, and is not always feasible to set a user-wide setting.

2024-09-13 15:52 UTC, Schaeff approved these changes
Fair enough then :)

2024-09-13 17:25 UTC, merged