riscv-executor: handle machines that have been optimized away
powdr-labs/powdr pull request #2222
Opened 2024-12-10 17:24 UTC by pacheco

2024-12-10 17:53 UTC, leonardoalt approved these changes

2024-12-10 17:59 UTC, leonardoalt requested changes
instruction tests failed locally (@pacheco told me)

2024-12-10 18:43 UTC, pacheco commented
Yeah, the original problem you mentioned is solved by this PR (machines being optimized away). 
What fails is a different issue with the same origin: asm optimizer removes instructions, which messes with selector assignment, which breaks manual witgen. To solve this the executor needs to take into account the optimized PIL...

2024-12-11 18:31 UTC, pacheco commented
I'm closing this for now

2024-12-11 18:31 UTC, closed without merging